# Site

title: PythonTask
url: "https://pythontask.pp.ua/"
baseurl:
google_analytics_key: UA-114344505-1
disqus_shortname: python-task
newsletter_action: "https://beregok.us14.list-manage.com/subscribe/post?u=c158cca56a371637105938e2a&amp;id=a5da6d3532"
# download_action: "https://github.com/pythontask/pythontask.github.io"
language:  "uk_UA"
# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Розв'язки задач з програмування на мові Python.
author:
  name: Berezhnyi Oleksandr
  email: beregok@gmail.com
  twitter: beregok # twitter username without the @ symbol
social:
  name: PythonTask
  links:
    - https://beregok.github.com/

# -----
# Build

permalink: /:categories/:title/
# permalink: pretty

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - README.md
  - license.md
  - CNAME
  - /.idea
  - /.git
  - /venv


sass:
    style: compressed


collections:
  sets:


jekyll-archives:
  enabled: ['categories']


algolia:
  application_id: RF70HVO6PG
  index_name: pythontask
  search_only_api_key: 3c0aed961ad322489afb215310c6bbd2


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"
# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
